CREATE DATABASE videotienda;
USE videotienda;

CREATE TABLE DOMINIOS (
TIPO_DOMINIO	VARCHAR(30)		NOT NULL,
ID_DOMINIO		VARCHAR(30)		NOT NULL,
VLRDOMINIO		VARCHAR(50)		NOT NULL,
CONSTRAINT PK_DOMINIOS PRIMARY KEY(TIPO_DOMINIO, ID_DOMINIO));

CREATE TABLE CATEGORIAS(
ID_CATEGORIA	INT		PRIMARY KEY IDENTITY(1,1),
NOM_CATEGORIA	VARCHAR(50)		NOT NULL);

CREATE TABLE PRODUCTORES(
ID_PROD		INT		PRIMARY KEY		IDENTITY(1,1),
NOM_PROD	VARCHAR(50)		NOT NULL);

CREATE TABLE PERSONAS(
NRO_DOC		NUMERIC(11)		PRIMARY KEY,
TIPO_DOC	VARCHAR(3)		NOT NULL,
NOMBRES		VARCHAR(50)		NOT NULL,
CELULAR		NUMERIC(11)		NOT NULL,
CORREO		VARCHAR(100)		NOT NULL,
DIRECCION	VARCHAR(100)		NOT NULL,
TIPO_PERSONA		VARCHAR(10)		NOT NULL,
CONTRASENA		VARCHAR(10)		NOT NULL);

CREATE TABLE ALQUILER(
ID_ALQUILER		INT		PRIMARY KEY		IDENTITY(1,1),
FEC_ALQUILER	DATE	NOT NULL,
FEC_DEVOLUCION	DATE	NOT NULL,
VLR_ALQUILER	DECIMAL(5,0)	NOT NULL,	
VLR_MULTAS		DECIMAL(5,0)	NOT NULL,
NRO_DOC			NUMERIC(11)		NOT NULL,
FOREIGN KEY (NRO_DOC) REFERENCES PERSONAS(NRO_DOC));

CREATE TABLE VIDEOJUEGOS(
NRO_REFERENCIA		INT			PRIMARY KEY		IDENTITY(1,1),
NOM_VIDEOJUEGO		VARCHAR(50)	NOT NULL,
IMG_VIDEOJUEGO		VARCHAR(100)	NOT NULL,
ID_PROD		INT		NOT NULL,
FOREIGN KEY (ID_PROD) REFERENCES PRODUCTORES(ID_PROD));

CREATE TABLE CAT_VIDEOJUEGOS(
ID_CAT_VIDEOJUEGO	INT		PRIMARY KEY		IDENTITY(1,1),
ID_CATEGORIA		INT		NOT NULL,
NRO_REFERENCIA		INT		NOT NULL,
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
FOREIGN KEY (NRO_REFERENCIA) REFERENCES VIDEOJUEGOS(NRO_REFERENCIA));

CREATE TABLE ALQ_VIDEOJUEGOS(
ID_ALQ_VIDEOJUEGO	INT		PRIMARY KEY		IDENTITY(1,1),
ID_ALQUILER		INT		NOT NULL,
NRO_REFERENCIA		INT		NOT NULL,
FOREIGN KEY (ID_ALQUILER) REFERENCES ALQUILER(ID_ALQUILER),
FOREIGN KEY (NRO_REFERENCIA) REFERENCES VIDEOJUEGOS(NRO_REFERENCIA));