CREATE DATABASE videotienda;
USE videotienda;

CREATE TABLE DOMINIOS (
TIPO_DOMINIO	VARCHAR(30)		NOT NULL,
ID_DOMINIO		VARCHAR(30)		NOT NULL,
VLRDOMINIO		VARCHAR(50)		NOT NULL,
CONSTRAINT PK_DOMINIOS PRIMARY KEY(TIPO_DOMINIO, ID_DOMINIO));